-- MySQL Script generated by MySQL Workbench
-- 06/22/17 21:43:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema simpleapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema simpleapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simpleapp` DEFAULT CHARACTER SET utf8 ;
USE `simpleapp` ;

-- -----------------------------------------------------
-- Table `simpleapp`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpleapp`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpleapp`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpleapp`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpleapp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpleapp`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(50) NULL,
  `email` VARCHAR(45) NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_users_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `simpleapp`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpleapp`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpleapp`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `body` VARCHAR(3000) NULL,
  `category_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`, `users_id`),
  INDEX `fk_article_category_idx` (`category_id` ASC),
  INDEX `fk_article_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_article_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `simpleapp`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `simpleapp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
